import React, { useEffect, useMemo, useState } from 'react';
import api from '../services/api';
import { formatDate } from '../utils/helpers';
import { Card, EmptyState, PageHeader, Section } from '../components/ui';

const metricCards = (summary) => {
  const planName = summary?.plan?.plan?.toUpperCase() || 'FREE';
  const maxJobs = Number(summary?.plan?.max_jobs || 0);
  const maxRunsPerDay = Number(summary?.plan?.max_runs_per_day || 0);
  const usedJobs = Number(summary?.usage?.total_jobs || 0);
  const runsToday = Number(summary?.usage?.runs_today || 0);

  return [
    {
      key: 'plan',
      label: 'Plan',
      value: planName,
      description: 'Current workspace plan.',
    },
    {
      key: 'jobs-remaining',
      label: 'Jobs Remaining',
      value: Math.max(maxJobs - usedJobs, 0),
      description: 'How many more jobs you can create.',
    },
    {
      key: 'runs-today',
      label: 'Runs Left Today',
      value: Math.max(maxRunsPerDay - runsToday, 0),
      description: 'Daily run quota still available.',
    },
    {
      key: 'exports',
      label: 'Total Exports',
      value: Number(summary?.usage?.total_exports || 0),
      description: 'Exports generated by this account.',
    },
  ];
};

const AccountPage = () => {
  const [summary, setSummary] = useState(null);
  const [jobs, setJobs] = useState([]);
  const [runs, setRuns] = useState([]);
  const [exports, setExports] = useState([]);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let mounted = true;

    Promise.all([api.getAccountSummary(), api.getJobs(), api.getRuns(), api.getExports()])
      .then(([summaryData, jobItems, runItems, exportItems]) => {
        if (!mounted) return;
        setSummary(summaryData);
        setJobs(Array.isArray(jobItems) ? jobItems : []);
        setRuns(Array.isArray(runItems) ? runItems : []);
        setExports(Array.isArray(exportItems) ? exportItems : []);
        setError('');
      })
      .catch(() => {
        if (!mounted) return;
        setSummary(null);
        setError('We could not load your account details right now.');
      })
      .finally(() => {
        if (mounted) setLoading(false);
      });

    return () => {
      mounted = false;
    };
  }, []);

  const metrics = useMemo(() => metricCards(summary), [summary]);

  const latestRuns = [...runs]
    .sort((left, right) => new Date(right?.started_at || 0) - new Date(left?.started_at || 0))
    .slice(0, 5);

  return (
    <section className="space-y-4">
      <PageHeader
        title="Account"
        description="See your current plan, usage, and recent activity at a glance."
      />

      {error ? (
        <Card className="border-red-400/25 bg-red-400/10 text-red-200" role="alert">
          {error}
        </Card>
      ) : null}

      {loading ? (
        <Card>
          <p className="text-sm text-slate-300">Loading account details...</p>
        </Card>
      ) : null}

      {!loading && summary ? (
        <>
          <div className="grid grid-cols-1 gap-3 md:grid-cols-2 lg:grid-cols-4">
            {metrics.map((metric) => (
              <Card key={metric.key} className="bg-slate-950">
                <p className="text-xs uppercase tracking-wide text-slate-500">{metric.label}</p>
                <p className="mt-1 text-2xl font-semibold text-slate-100">{metric.value}</p>
                <p className="mt-1 text-xs text-slate-400">{metric.description}</p>
              </Card>
            ))}
          </div>

          <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
            <Section title="Usage details" description="How this account is currently consuming resources.">
              <ul className="space-y-2 text-sm text-slate-300">
                <li>Total jobs: {Number(summary?.usage?.total_jobs || 0)}</li>
                <li>Total runs: {Number(summary?.usage?.total_runs || 0)}</li>
                <li>Total exports: {Number(summary?.usage?.total_exports || 0)}</li>
                <li>Runs today: {Number(summary?.usage?.runs_today || 0)}</li>
              </ul>
            </Section>

            <Section title="Workspace totals" description="Current object counts in your workspace.">
              <ul className="space-y-2 text-sm text-slate-300">
                <li>Saved jobs: {jobs.length}</li>
                <li>Recorded runs: {runs.length}</li>
                <li>Saved exports: {exports.length}</li>
              </ul>
            </Section>
          </div>

          <Section title="Recent runs" description="Latest run activity and outcomes.">
            {latestRuns.length === 0 ? (
              <EmptyState
                title="No recent runs yet."
                description="Start a run from Home and it will appear here."
              />
            ) : (
              <ul className="space-y-2">
                {latestRuns.map((run) => (
                  <li key={run.id} className="rounded-xl border border-white/10 bg-slate-900 p-3">
                    <div className="flex flex-wrap items-center justify-between gap-2 text-sm">
                      <p className="font-medium text-slate-100">Run #{run.id}</p>
                      <span className="rounded-full border border-white/10 px-2 py-1 text-xs text-slate-300">
                        {String(run.status || 'unknown')}
                      </span>
                    </div>
                    <p className="mt-1 text-xs text-slate-400">Started {formatDate(run.started_at)}</p>
                  </li>
                ))}
              </ul>
            )}
          </Section>
        </>
      ) : null}
    </section>
  );
};

export default AccountPage;
